### ISSUE TITLE
Lack of Installation Instructions for iPhone

### ISSUE THREAD

**Issue by fischerNoah** [NarekPVP/simple-chat-mobile#1]
There seems to be no clear instructions on how to install and launch the application on iOS platform. I've searched through the repository's documentation and README files, but I couldn't find any guidance specific to iOS or iPhone usage. Could you please provide detailed instructions on how to install and run your program on an iPhone, or point me to existing documentation if I've overlooked it?

**Comment by NarekPVP** [comment]
@fischerNoah It's not ready yet.
